const WORDLIST = [
  "abacus","abdomen","abdominal","abide","abiding","ability","ablaze","able",
  "abnormal","abrasion","abrasive","abreast","absence","absentee","absorb","abstract",
  "absurd","abuse","academy","accent","acclaim","acclimate","accompany","account",
  "accuracy","accurate","accuse","acetic","achieve","acid","acidity","acme",
  "acorn","acoustics","acquire","acreage","acrobat","acronym","acrylic","acting",
  "action","activate","activator","active","activism","actor","actress","acutely",
  "adapter","addicted","addition","additive","address","adenoid","adept","adhesive",
  "adjacent","adjust","admin","admiral","adoption","adorable","adornment","adult",
  "advanced","adventure","adverse","advocacy","advocate","aerial","aerobics","aerospace",
  "affable","affair","affected","affection","affiliate","affirm","affluent","afford",
  "affront","aflame","afraid","afterglow","afterlife","aftermath","afternoon","aging",
  "agitate","agnostic","agonize","agony","agreeable","agreement","aground","ahead",
  "ailment","aimless","airborne","aircraft","airfare","airfield","airlift","airline",
  "airmail","airplane","airport","airspace","airtight","airway","aisle","alarm",
  "albatross","album","alchemy","alcohol","alderman","ale","alertness","algebra",
  "algorithm","alias","alibi","alien","alignment","alimony","alkaline","almanac",
  "almond","almost","aloe","alongside","alphabet","already","also","altitude",
  "aluminum","alumni","always","amazed","amazement","amazing","amazon","ambiance",
  "ambiguity","ambiguous","ambition","ambitious","ambulance","ambush","amendment","amends",
  "amenity","amiable","amicable","ammonia","amnesty","amoeba","amount","amperage",
  "ample","amplifier","amplify","amulet","amusement","anaconda","anagram","analog",
  "analyst","analyze","anatomy","anchor","ancient","android","anecdote","anemia",
  "anesthetic","angel","anger","angled","angler","angry","anguish","animal",
  "animate","ankle","annex","annotate","announce","annual","annuity","anomaly",
  "anonymity","anonymous","another","answer","antacid","antenna","anthem","anthill",
  "anthology","antidote","antihero","antiquity","antisocial","antiviral","antler","anxiety",
  "anybody","anyhow","anything","anywhere","apartment","apathy","aperture","apex",
  "apnea","apologize","apology","apostle","apparel","apparent","appeal","appetizer",
  "applaud","apple","appliance","applicant","applied","appointee","appraisal","appreciable",
  "approval","approve","apricot","april","apron","aquarium","aquatic","aqueduct",
  "arbitrary","arbitrate","arcade","archaeologist","archer","archetype","archive","arctic",
  "ardently","arena","arguably","argue","argument","arise","armadillo","armband",
  "armchair","armoire","armor","armrest","army","aroma","aromatic","around",
  "arousal","arrange","array","arrest","arrival","arrive","arrogance","arrogant",
  "arrow","arsenal","arson","arterial","artery","artful","article","artifact",
  "artificial","artisan","artistry","artwork","ascend","ascension","ascertain","aside",
  "askew","asleep","asparagus","aspect","asphalt","aspirant","aspire","assemble",
  "assertive","assess","asset","assign","assist","associate","assume","assurance",
  "asteroid","asthma","astound","astronomy","asylum","atelier","athlete","atlas",
  "atmosphere","atom","atrium","atrocious","attach","attain","attempt","attendant",
  "attention","attic","attitude","attorney","attract","attribute","auction","audacity",
  "audible","audience","audio","audit","augmented","august","authentic","author",
  "automaker","automated","autonomy","autopilot","autumn","auxiliary","avalanche","avenge",
  "avenue","average","aviation","avid","avocado","avoid","awaken","award",
  "awesome","awful","awkward","awning","axle","babble","baboon","backache",
  "backbone","backdrop","backfield","backfire","backhand","backlog","backpack","backstage",
  "backup","backward","backyard","bacon","bacteria","badge","badger","badlands",
  "badly","baffle","bagel","baggage","bagpipe","baguette","bailiff","bakery",
  "balancing","balcony","baldness","ballad","ballerina","ballet","balloon","ballot",
  "bamboo","banana","bandage","bandit","banister","banjo","bankbook","banker",
  "banking","bankrupt","banner","banquet","banter","barbed","barbell","barber",
  "barge","bargraph","barista","baritone","barley","barn","barracks","barrel",
  "barrier","bartender","barter","baseball","baseline","basement","basic","basil",
  "basin","basis","basket","basketball","bassoon","batch","bathrobe","bathroom",
  "bathtub","battalion","battery","battle","bazooka","beacon","beagle","beanstalk",
  "bearable","beard","beast","beatnik","beauty","beaver","because","become",
  "bedrock","bedroom","bedside","bedspread","bedtime","beehive","beekeeper","beetle",
  "behavior","behind","beige","believe","beloved","below","benchmark","benefit",
  "benign","beside","besides","bespoke","bestow","betrayal","better","beverage",
  "bewilder","beyond","bicycle","bidding","bigfoot","biggest","bikini","billion",
  "bimonthly","binoculars","biography","biology","biopsy","biotech","birdbath","birdcage",
  "birdhouse","birthday","biscuit","bishop","bistro","blackbird","blackboard","blackjack",
  "blacklist","blackmail","blackout","blacksmith","bladder","blade","blanket","blasphemy",
  "blast","blatant","blaze","blazer","bleach","bleak","blemish","blessing",
  "blimp","blindfold","blindly","bliss","blister","blizzard","bloat","blockade",
  "blogger","bloodbath","bloodhound","bloodshed","bloodshot","blouse","blowfish","blubber",
  "blueberry","bluebird","blueprint","blunder","blunt","boardroom","boastful","bobbin",
  "bobcat","bobsled","bodyguard","bodysuit","bodywork","boggle","bohemian","boiling",
  "boldly","bolster","bombard","bonanza","bondage","bonfire","bookcase","bookend",
  "booklet","bookmark","bookshelf","bookworm","boolean","boomerang","boost","bootcamp",
  "booth","border","boredom","boring","borough","borrower","bosom","botanical",
  "botanist","botany","botch","both","bottle","bottleneck","bottom","boulder",
  "boulevard","bounce","boundary","bounty","bouquet","boutique","bovine","bowler",
  "bowling","bracelet","bracket","bragging","braid","braille","bramble","branch",
  "brand","brandy","brash","brass","bravado","bravery","brazen","breach",
  "breadth","breakaway","breakdown","breakfast","breakneck","breakthrough","breathe","breeze",
  "brevity","brewery","bribery","brickwork","bridal","briefcase","briefly","brigade",
  "brilliant","brimstone","bristle","broadcast","broccoli","brochure","broiler","broken",
  "broker","bronchial","bronze","brooding","brookside","browbeat","browser","brunette",
  "brushwork","brutality","brutally","bubble","buccaneer","buckle","buckshot","buckskin",
  "buddhism","buddy","budget","buffalo","buffet","bugle","builder","building",
  "bulkhead","bulldozer","bulletin","bullfrog","bullhorn","bullion","bullpen","bumblebee",
  "bumbling","bungalow","bunion","bunkmate","bunny","burden","bureau","burger",
  "burglary","burial","burlap","burnish","burrito","burrow","busboy","bushel",
  "business","busload","butchery","butler","buttercup","butterfly","buttermilk","butternut",
  "cabin","cabinet","cactus","cadaver","cadence","cadet","cafeteria","caffeine",
  "calcium","calculate","calendar","caliber","calibrate","caliper","calling","calm",
  "calorie","campaign","campfire","campsite","campus","canal","canary","cancel",
  "candidate","candle","candlestick","canister","cannabis","cannonball","canopy","canteen",
  "canvas","canyon","capable","capacity","capital","capsule","captain","caption",
  "captivate","captive","capture","caramel","carbon","cardboard","cardinal","career",
  "carefree","careful","careless","caretaker","cargo","caribou","caring","carnival",
  "carol","carpet","carriage","carrier","carrot","carrying","cartridge","cascade",
  "cashew","cashmere","cashier","casino","casket","cassette","casualty","catalog",
  "catalyst","catapult","category","catering","caterpillar","cathedral","catnip","cauliflower",
  "caution","cautious","cavalier","cavalry","caveman","caviar","cavity","cease",
  "cedar","ceiling","celebrate","celebrity","celery","celestial","cement","cemetery",
  "census","centennial","center","central","ceramic","ceremony","certain","certainly",
  "chairman","challenge","champion","chandelier","channel","chapter","character","charcoal",
  "charity","charming","charter","chassis","cheap","checkbox","checkout","cheekbone",
  "cheerful","chemical","chemistry","cherry","chess","chestnut","chicken","childhood",
  "chili","chimney","china","chipboard","chipmunk","chocolate","choir","chokehold",
  "cholesterol","choosing","choreograph","chorus","chronicle","chrysalis","chuckle","chunk",
  "cinema","cinnamon","circle","circuit","circular","circulate","circumvent","citadel",
  "citizen","citrus","civilize","clairvoyant","clamber","clammy","clamor","clampdown",
  "clapboard","clarify","clarinet","clarity","classify","classmate","classroom","cleanup",
  "clearance","clearing","cleavage","clergyman","clerical","clerk","clever","climate",
  "climbing","clinic","clinical","clipboard","clockwork","closeness","closure","clothespin",
  "cloudless","clutter","coachman","coalition","coastal","cobblestone","cobweb","cockpit",
  "coconut","codebook","cognition","coherent","cohesive","coincide","coliseum","collapse",
  "collarbone","colleague","collector","collision","colonial","colonist","colony","colorado",
  "colossal","columnist","combustion","comeback","comedian","comet","comfort","commander",
  "commence","comment","commerce","commission","committee","commodity","commoner","commotion",
  "communal","community","commute","companion","company","compare","compass","compel",
  "competent","compile","complaint","complete","complex","compliant","component","compose",
  "composite","compost","compound","compress","compute","computer","conceal","concede",
  "conceive","concept","concern","concert","conclude","concrete","condition","conduct",
  "confess","confetti","confident","confine","confirm","conflict","conform","confront",
  "confuse","congress","connect","conquer","conscious","consensus","consent","conserve",
  "consider","consist","console","conspire","constant","construct","consult","consumer",
  "contact","contain","contempt","content","contest","context","continent","contract",
  "contrast","contribute","control","convene","convent","converge","convince","cookbook",
  "cookie","coolness","cooperate","copyright","coral","cordial","corkscrew","cornbread",
  "corner","cornfield","cornstarch","corporate","correct","corridor","corrode","corrupt",
  "corsage","cosmetics","cosmic","cosmos","costume","cottage","cotton","council",
  "countdown","counter","countless","country","county","couple","courage","courier",
  "courtesy","courtroom","courtyard","cousin","coverage","covert","cowhide","crackdown",
  "cracker","cradle","craftsman","crampons","cranberry","crane","cranium","crayfish",
  "creative","creature","credible","cricket","criminal","crimson","crisis","crisp",
  "criteria","critical","critique","critter","crochet","croissant","crossbow","crossover",
  "crossword","crowbar","crucial","cruelty","cruise","crumble","crusader","crystal",
  "cubbyhole","cucumber","cultivate","cultural","cupboard","cupcake","curator","curfew",
  "curiosity","curious","currency","current","curtain","cushion","custard","customer",
  "customize","cutback","cycling","cyclone","cylinder","cymbal","cynicism",
];

export interface PassphraseOptions {
  wordCount?: number;
  separator?: string;
  capitalize?: boolean;
}

export function generatePassphrase(opts: PassphraseOptions = {}): string {
  const { wordCount = 6, separator = "-", capitalize = false } = opts;
  const indices = new Uint32Array(wordCount);
  crypto.getRandomValues(indices);
  const words = Array.from(indices).map((n) => {
    const word = WORDLIST[n % WORDLIST.length]!;
    return capitalize ? word.charAt(0).toUpperCase() + word.slice(1) : word;
  });
  return words.join(separator);
}

export function generatePassphrases(count: number, opts: PassphraseOptions = {}): string[] {
  return Array.from({ length: count }, () => generatePassphrase(opts));
}

export function estimatePassphraseEntropy(wordCount: number): number {
  return Math.floor(wordCount * Math.log2(WORDLIST.length));
}

export function passphraseWordlistSize(): number {
  return WORDLIST.length;
}
